#!/usr/bin/env python3
#
# Copyright 2026 RFC-Tsudanuma
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the “Software”), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# [Contributors]
#
# - Satoshi Inoue

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: teammate_communication.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'teammate_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cteammate_communication.proto\x12\x16teammate_communication\"A\n\rLocalPosition\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\r\n\x05valid\x18\x04 \x01(\x08\"B\n\x0eGlobalPosition\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\r\n\x05valid\x18\x04 \x01(\x08\"\xad\x02\n\x14TeamCommunicationMsg\x12\x12\n\nvalidation\x18\x01 \x01(\x05\x12\x10\n\x08robot_id\x18\x02 \x01(\x05\x12\x37\n\x07selfpos\x18\x03 \x01(\x0b\x32&.teammate_communication.GlobalPosition\x12\x37\n\x07\x62\x61llpos\x18\x04 \x01(\x0b\x32&.teammate_communication.GlobalPosition\x12<\n\rballpos_local\x18\x05 \x01(\x0b\x32%.teammate_communication.LocalPosition\x12*\n\x04role\x18\x06 \x01(\x0e\x32\x1c.teammate_communication.Role\x12\x13\n\x0bstrategy_hz\x18\x07 \x01(\x02*\"\n\tCoordType\x12\t\n\x05LOCAL\x10\x00\x12\n\n\x06GLOBAL\x10\x01*;\n\x04Role\x12\n\n\x06KEEPER\x10\x00\x12\x0c\n\x08\x44\x45\x46\x45NDER\x10\x01\x12\x0c\n\x08\x41TTACKER\x10\x02\x12\x0b\n\x07NEUTRAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'teammate_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COORDTYPE']._serialized_start=495
  _globals['_COORDTYPE']._serialized_end=529
  _globals['_ROLE']._serialized_start=531
  _globals['_ROLE']._serialized_end=590
  _globals['_LOCALPOSITION']._serialized_start=56
  _globals['_LOCALPOSITION']._serialized_end=121
  _globals['_GLOBALPOSITION']._serialized_start=123
  _globals['_GLOBALPOSITION']._serialized_end=189
  _globals['_TEAMCOMMUNICATIONMSG']._serialized_start=192
  _globals['_TEAMCOMMUNICATIONMSG']._serialized_end=493
# @@protoc_insertion_point(module_scope)
